{% set name = "glimix-core" %}
{% set version = "1.2.26" %}
{% set sha256 = "3bd87af4f54b9b6291d27ab568ca85834992be391f845de6778ec4c15191710e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - scipy >=0.19.0
    - hcephes >=0.2.3
    - numpy >=1.11
    - numpy-sugar >=1.2.3
    - scipy-sugar >=1.0.6
    - optimix >=1.2.23
    - cachetools >=2.0
    - tqdm >=4.19
    - liknorm >=1.3.11
    - liknorm-py >=1.0.12
    - numba >=0.35
    - toolz >=0.8

test:
  requires:
    - pytest >=3
    - pytest-pep8
  imports:
    - glimix_core
  commands:
    - python -c "import glimix_core"

about:
  home: https://github.com/limix/glimix-core
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Fast inference for Generalized Linear Mixed Models'
  doc_url: https://glimix-core.readthedocs.io/
  dev_url: https://github.com/limix/glimix-core

extra:
  recipe-maintainers:
    - Horta
