{% set name = "glimix-core" %}
{% set version = "2.0.5" %}
{% set sha256 = "9791eb7b89ccd78f0b89526a8a83841c6dbf851e1030d64e0d8af7a387133d3c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win and py27]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - pip
    - pytest-runner
    - python
    - setuptools >=39.0.1
    - wheel
  run:
    - brent-search >=1.0.33
    - cachetools
    - cytoolz
    - liknorm >=1.4.6
    - liknorm-py >=1.1.13
    - ndarray-listener >=1.1.2
    - numpy >=1.14.5
    - numpy-sugar >=1.2.5
    - optimix >=2.0.0
    - pandas >=0.23.3
    - pytest
    - python
    - scipy >=1.1.0
    - scipy-sugar >=1.0.7
    - tqdm >=4.23.4
    - pytest-doctestplus >=0.1.3

test:
  requires:
    - pytest
  imports:
    - pandas
    - glimix_core
  commands:
    - python -c "import sys; import glimix_core; sys.exit(glimix_core.test())"

about:
  home: https://github.com/limix/glimix-core
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Fast inference for Generalized Linear Mixed Models'
  doc_url: https://glimix-core.readthedocs.io/
  dev_url: https://github.com/limix/glimix-core

extra:
  recipe-maintainers:
    - Horta
