{% set name = "glimix-core" %}
{% set version = "3.1.8" %}
{% set sha256 = "d92a9b9fcb4d4891e6118831f09e0a696882f555db73e74a14a4b98d111a7a96" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - pytest-runner
    - python >3
    - setuptools >=39.0.1
    - wheel
  run:
    - brent-search >=2.0.0
    - cachetools
    - cytoolz
    - liknorm >=1.5.1
    - liknorm-py >=1.2.2
    - ndarray-listener >=2.0.0
    - numpy >=1.14.5
    - numpy-sugar >=1.5.0
    - optimix >=3.0.3
    - pandas >=0.25.1
    - pytest
    - python >3
    - scipy >=1.1.0
    - scipy-sugar >=1.0.9
    - tqdm >=4.23.4
    - pytest-doctestplus >=0.4.0
    - statsmodels >=0.9.0

test:
  requires:
    - pytest
  imports:
    - pandas
    - glimix_core
  commands:
    - python -c "import sys; import glimix_core; sys.exit(glimix_core.test())"

about:
  home: https://github.com/limix/glimix-core
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Fast inference for Generalized Linear Mixed Models'
  doc_url: https://glimix-core.readthedocs.io/
  dev_url: https://github.com/limix/glimix-core

extra:
  recipe-maintainers:
    - Horta
