{% set name = "glimix-core" %}
{% set version = "1.3.2" %}
{% set sha256 = "eede67cfec2dec24ff8434d023b115e1bf692d42161c3bcf9d0c654a77db7a99" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - pytest-runner
  run:
    - python
    - scipy >=0.18.1
    - hcephes >=0.2.3
    - numpy >=1.10
    - numpy-sugar >=1.1.2
    - scipy-sugar >=1.0.4
    - optimix >=1.2.21
    - cachetools >=2.0
    - tqdm >=4
    - liknorm >=1.3.11
    - liknorm-py >=1.0.12
    - numba >=0.32
    - toolz

test:
  requires:
    - pytest >=3
    - pytest-pep8
    - pytest-sugar
  imports:
    - glimix_core
  commands:
    - python -c "import sys; import glimix_core; sys.exit(glimix_core.test())"

about:
  home: https://github.com/limix/glimix-core
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Fast inference for Generalized Linear Mixed Models'
  doc_url: https://glimix-core.readthedocs.io/
  dev_url: https://github.com/limix/glimix-core

extra:
  recipe-maintainers:
    - Horta
