{% set name = "glimix-core" %}
{% set version = "1.4.1" %}
{% set sha256 = "a74bdbbd6e1101039fb8dfbb8c65a2884b935a634acd73fa1174b9185fc0a352" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools >=39.0.1
    - pytest-runner
  run:
    - python
    - pytest-pep8 >=1.0.6
    - pytest >=3.3.2
    - brent-search >=1.0.32
    - scipy >=1.0.0
    - hcephes >=0.2.3
    - ndarray-listener >=1.1.1
    - numpy >=1.14.0
    - numpy-sugar >=1.2.3
    - scipy-sugar >=1.0.6
    - optimix >=1.2.23
    - cachetools >=2.0.1
    - tqdm >=4.19.4
    - liknorm >=1.3.11
    - liknorm-py >=1.0.12
    - toolz >=0.9
    - pandas >=0.22.0

test:
  requires:
    - pytest >=3
    - pytest-pep8
  imports:
    - import pandas
    - glimix_core
  commands:
    - python -c "import sys; import glimix_core; sys.exit(glimix_core.test())"

about:
  home: https://github.com/limix/glimix-core
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Fast inference for Generalized Linear Mixed Models'
  doc_url: https://glimix-core.readthedocs.io/
  dev_url: https://github.com/limix/glimix-core

extra:
  recipe-maintainers:
    - Horta
