{% set name = "glimix-core" %}
{% set version = "1.2.19" %}
{% set sha256 = "9a6e6cce9aee8c6f63d463e087a2575abd99f622ceec5a2755ddc20fa474c0de" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: true  # [win32 or linux32 or (win64 and py27)]
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - ncephes >=1.0.40
  run:
    - python
    - scipy >=0.18.1
    - ncephes >=1.0.40
    - numpy >=1.10
    - numpy-sugar >=1.0.47
    - scipy-sugar >=1.0.2
    - optimix >=1.2.13
    - cachetools >=2.0
    - tqdm >=4
    - liknorm-py >=1.0.6
    - numba >=0.32

test:
  requires:
    - pytest >=3
    - pytest-pep8
  imports:
    - glimix_core
  commands:
    - python -c "import sys; import glimix_core; sys.exit(glimix_core.test())"

about:
  home: https://github.com/limix/glimix-core
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Fast inference for Generalized Linear Mixed Models'
  doc_url: https://glimix-core.readthedocs.io/
  dev_url: https://github.com/limix/glimix-core

extra:
  recipe-maintainers:
    - Horta
