travis:
  secure:
    BINSTAR_TOKEN: JjOsjsaSKB6JDrgl21JIwET7MBfeqNoYNn8UUMaPnXu++0EZf6aq+UasXfbp8swWMZY2IH27ROs6brqURN9HDHSvyASfarAobUJKZVy5f/kATbEiN7HoIdZq/bUjA/alrHhDMcyhp58ykmDJAKoFwieBekleUB+gQMfnqu/ZXzBzCwI1KcWfum2hfrAwZIuGN0AOhkzDzXCmjqlPnhcBEM8QcIhO2dqeInDY7N1SeBpwfmA9bpQaSc3n2wu/5yEHwnfjzUb4UAAT3LzaTzz4E/6oYsfaIWDbvWxP+J6H86o+H2upJqNK4StlHMnEB+I8K3t0wDr4DqkQQkHVM2nMpn9Frs4JsXj6LJzoz3555djv6q29sxUbnwAduVoQB8b6j5hHrIGLy9IDSbdCFNErZASK+nrECp7O0F3Zs/2JMvDKYg2ul+1D9V1YUnwUn743UWfdkJ1irI6E9MwjCeIpo6FcvLAAJ4US/RHRYXNuvVCtj8i7SCRTiVLkCWWx7s6EXp2+hKZjlViREha589+b1KneQhIm+UMvCRKbSXU0IsDJosCpqIrIB0ql21nXun9QLJaR1YEHt5TV/fhfPnSzLJLoc1gHMvgpQZm17xtA3R6Yve+L0XrlWir2A9D4VKzknZEv72kZvcMTwuNd3Pq2cCdyb16zWpIF3pay/ar9hJ0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
