travis:
  secure:
    BINSTAR_TOKEN: qqpVVZvSpB9k+9vueajqYEVOjDOMs3Ow69V+wNyp5L3prCk6Bh03CWMoDvOf2OFI447dqY9iO0woWn5UHEyl6mTXrqQ1WrVfjmXkRNT6zormrfvEjluLzTx5tm9FLt1cRCI49dK4m+WBrdR3NafQQxcEhT8FboH5x7rt72kPPIB8PHQvF0sx63hUWM+FzobJvIahnGYzJfVBeYOg++KTmv4JS2sCGsOhX+aLqHlhlPGUYOAn5vdcsu9GtsrAHjNSCFgX5s0AT6S211zfA2YFuguhwjUTdvd/U3UpqdpPbMEH/NQW+uDwRe4saim6SDT+qoYjbow54kM+c+esaGRFNl5OmgUu/MH3nFOa7rOS519k0Pl1w8ygia0prLAT05/hF9Av3Ns9wZ/EpNU8nMOm2sZ+j/hytCPkpZoTFCkmYE4sttzC2k3P/6+BDuzE+RzG1AjcNvoquudDbnk+ZQBLQbFYII++94CPQTB855IVgd1HeYKe0DWAQkI/sVzNA4DGkE5c4Kuw54jV98PuZsAVSG50JfEx/y0dZcK4qX9E0rlfXvR7F7DW1oe5H3XhTUT9cChUk7hSLT7V0dxPiHmhMPFvSsjc52HvifOHJqLLOPSuZyfyr6IiJzy5sRLuwRUne5GzwcnDTU0jHL6zbj0Klc2kJ3AJNFh165HFE1/3ae4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
