travis:
  secure:
    BINSTAR_TOKEN: koa5xwk8UwS9u/7sJW3xEO31IQyW2yYOkNRWswna+/Jh0iiDh1Bjx3sSiprpo60w4g0JXtm0mbmlzoG0AvsnmX0DHn3dgY3A7wYNIDy/zC1NY7Sz/SI3qLRev+osF9f5T6wHJHh4TquYXFOLe62n98ewtgl8D6tSPofJ8SKFRKYSK5lo2AcukbQyasv3L1YXIrP4acWKIyT3IVltTjRUzOKvV8wR/1CkjL7xLjqWhWwkVgEVtKGR7XHEgYxZ4sJZHrrk1mFcsqSEUOM2sXvB/oDFIExaUSJyIHM4HcjA1blPaXSaupW5adhAmisRNGmJvQtNsZ+F7TQ3NR6LFcmwBtgiu7pXdLxfCivtsSYlZ4egAshLK8CZIlo6/BEKmhpguqNHoiGCWm/UfJ7ZDS78CMAKPTropFLpR1TiNoLwXGLPW3oRMaVJMu7axDtw99g8VGmfNUOvpa9Fq64sqPv/4Qzb+P/6E5y3UtVDmw/ZlrUxWSZd2b9ZfEg/pAP2KfZu2R81ouTkogxhnOYHo+80VLuBfeHhppoBbd+nvBe6Rn/q9XjoBXFb57gdy1J4DgyANP3Md++uRlwV7sjTkL9ZgK6A9YKoPnlv69LTprbUdu77llSWeOGfk+J5FamPNGdBhKHtw9SH/2LDyv3kDwv1yocTrauR63ljwSoTcUV60cg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
